rosmip_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

rosmip_imu_controller:
  type: imu_sensor_controller/ImuSensorController
  publish_rate: 50

rosmip_balance_controller:
    type: rosmip_control/RosMipControllerLegacy

    odom_ws: 0.0823
    odom_lr: 0.0299
    odom_rr: 0.0299

    d1_num: [-4.945, 8.862, -3.967]
    d1_den: [1.000, -1.481, 0.4812]
    d1_gain: 0.75

    d2_num: [0.18856, -0.37209, 0.18354]
    d2_den: [1.00000, -1.86046, 0.86046]
    d2_gain: 0.9

    d3_kp: 0.7
    d3_kd: 0.05
    d3_ki: 0.3
    d3_sat: 0.5

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    