<?xml version="1.0"?>
<robot name="rosmip" xmlns:xacro="http://www.ros.org/wiki/xacro">

  
  
  <!-- Dimensions -->
  <xacro:property name="PI" value="3.1415926535897931" />

  <!-- <xacro:property name="chassis_length" value="0.035" /> -->
  <!-- <xacro:property name="chassis_width"  value="0.062" /> -->
  <!-- <xacro:property name="chassis_height" value="0.12" /> -->
  <!-- <xacro:property name="chassis_mass"   value="0.18" /> -->
  <!-- <xacro:property name="chassis_vert_offset" value="0.055" /> -->

  <!-- <xacro:property name="wheel_radius" value="0.03" /> -->
  <!-- <xacro:property name="wheel_width"  value="0.01" /> -->
  <!-- <xacro:property name="wheel_track"  value="0.083" /> -->
  <!-- <xacro:property name="wheel_mass"   value="0.01" /> -->
  <!-- <xacro:property name="wheel_joint_damping" value="0.01" /> -->
  <!-- <xacro:property name="wheel_joint_friction" value="0.01" /> -->

  <!-- appearance -->
  <!-- <xacro:property name="high_definition_wheel_visual" value="true" /> -->
  <!-- <xacro:property name="high_definition_body_visual" value="false" /> -->

  <xacro:include filename="$(find common_robots)/urdf/sensors.urdf.xacro" />
  

  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <!-- infrared marker -->
  <!-- <xacro:property name="use_infrared_marker" value="true" /> -->
  
  <!-- Inertia macros -->
  <xacro:include filename="$(find rosmip_description)/urdf/inertias.urdf.xacro" />
  
  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix wheel_radius lr_reflect *joint_pose">
    <xacro:property name="wheel_mesh_scale" value="${wheel_radius/0.03}" />
    <link name="${prefix}_wheel_link">
      <visual>
	<xacro:unless value="${high_definition_wheel_visual}">
	  <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
          <geometry>
	    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <material name="yellow" />
	</xacro:unless>
	<xacro:if value="${high_definition_wheel_visual}">
	  <origin xyz="0 0 0" rpy="0 0 ${lr_reflect*PI/2}"/>
          <geometry>
	    <mesh scale="1. ${wheel_mesh_scale} ${wheel_mesh_scale}" filename="package://rosmip_description/meshes/wheel_60.dae"/>
          </geometry>
	</xacro:if>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder_with_pose mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_width}">
	<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      </xacro:inertial_cylinder_with_pose> 
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
    
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
      <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
      <limit effort="1" velocity="10"/>
    </joint>

    
    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel_joint">
	<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
	<mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>



  <xacro:wheel prefix="left" wheel_radius="${left_wheel_radius}" lr_reflect="1">
    <origin xyz="0 ${(wheel_track-wheel_width)/2} 0" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="right"  wheel_radius="${right_wheel_radius}" lr_reflect="-1">
    <origin xyz="0 ${-(wheel_track-wheel_width)/2} 0" rpy="0 0 0" />
  </xacro:wheel>



  
  <!-- Body -->
  <link name="base_link"></link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis_link" />
  </joint>

  <link name="chassis_link">
    <visual>
	<xacro:if value="${high_definition_body_visual}">
	  <origin xyz="0.009 0 ${chassis_vert_offset-0.025}" rpy="${pi/2} 0 ${pi/2}"/>
	  <geometry>
	    <!--<mesh filename="package://rosmip_description/meshes/body_minion.dae"/>-->
	    <!--<mesh filename="package://rosmip_description/meshes/body_murat.dae"/>-->
	    <mesh filename="package://rosmip_description/meshes/rosmip_chassis.dae"/>
	  </geometry>
	</xacro:if>
	<xacro:unless value="${high_definition_body_visual}">
	  <origin xyz="0 0 ${chassis_vert_offset}" rpy="0 0 0"/>
	  <geometry>
	    <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
	  </geometry>
	  <material name="yellow" />
	</xacro:unless>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_vert_offset}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_cuboid_with_pose mass="${chassis_mass}" x_length="${chassis_length}" y_length="${chassis_width}" z_length="${chassis_height}">
      <origin xyz="0.00  0.00 ${chassis_vert_offset}" rpy="0 0 0"/>
    </xacro:inertial_cuboid_with_pose> 
  </link>

  <!--
   <gazebo reference="chassis_link">
    <material>Gazebo/YellowTransparent</material>
  </gazebo>
  -->

  <!-- Infrared Marker -->
  <xacro:if value="${use_infrared_marker}">
    <xacro:cs_smocap_ir_marker mesh="${smocap_ir_marker_mesh}">
      <origin xyz="0. 0. 0.092" rpy="0 0 0" />
    </xacro:cs_smocap_ir_marker>
  </xacro:if>
 

  <!-- Aruco Marker -->
  <xacro:if value="${use_aruco_marker}">
    <xacro:arg name="root_link" default="irm_link"/>
    <xacro:arg name="marker_texture" default="Aruco14"/>
    <xacro:include filename="$(find smocap)/urdf/chessboard.urdf.xacro" />
    <xacro:property name="chsbrd_dx"   value="0.05" />
    <xacro:property name="chsbrd_dy"   value="0.05" />
    <xacro:property name="chsbrd_dz"   value="0.0025" />
    <xacro:chessboard root_link="$(arg root_link)" texture="$(arg marker_texture)" static="false"/>

    <xacro:property name="irm_z" value="0.098" />

    <joint name="irm_joint" type="fixed">
      <origin xyz="0.0025 0 ${irm_z}" rpy="0 0 0" />
      <parent link="chassis_link"/>
      <child link="irm_link" />
    </joint>

    
  </xacro:if> 
  
  <!-- IMU -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 ${chassis_vert_offset}" rpy="${PI/2} 0 ${PI/2} " />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>
  <!-- Camera -->
  <xacro:if value="${use_eachine_camera}">
    <xacro:property name="cam_look_down_deg" value="0." />
    <xacro:cs_camera_eachine>
      <origin xyz="0.025 0 0.085" rpy="0 ${cam_look_down_deg/180*pi}} 0" />
    </xacro:cs_camera_eachine>
  </xacro:if>

  
  <gazebo reference="imu_link">
  
  </gazebo>

  
  <!-- Bring in simulation data for Gazebo. -->
  <xacro:include filename="$(find rosmip_description)/urdf/rosmip.gazebo" />


  
</robot>
